spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/finvault
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  liquibase:
    contexts: docker
    
logging:
  level:
    root: INFO
    com.finvault: DEBUG
