spring:
  application:
    name: finvault
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
  
  jwt:
    secret: ${JWT_SECRET}
    expiration: 86400000

gemini:
  api:
    key: ${GEMINI_API_KEY}

management:
  server:
    port: 9090
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics,loggers,env
  endpoint:
    health:
      show-details: when-authorized
      roles: ADMIN
    loggers:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
    distribution:
      percentiles-histogram:
        http.server.requests: true
      minimum-expected-value:
        http.server.requests: 5ms
      maximum-expected-value:
        http.server.requests: 10s
